baseURL: https://example.org/
title: Matty Kakes Makes
theme: tailbliss
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: false
pagination:
  pagerSize: 2
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

