baseURL: https://mattykakesmakes.com/
title: Matty Kakes Makes
# theme: tailbliss
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: false
pagination:
  pagerSize: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

