main:
  - identifier: project
    name: Projects
    url: /categories/project/
    weight: 10
  - identifier: blog
    name: Blog
    url: /categories/blog/
    weight: 20
  - identifier: about
    name: About
    url: /about/
    weight: 30
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 40
footer:
  - identifier: project
    name: Projects
    url: /categories/project/
    weight: 10
  - identifier: blog
    name: Blog
    url: /categories/blog/
    weight: 20
  - identifier: about
    name: About
    url: /about/
    weight: 30
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 40