[phases.setup]
aptPkgs = ["hugo"]
nixPkgs = ["nodejs_24"]

[environment]
HUGO_VERSION = "0.152.2"

[variables]
HUGO_ENABLEGITINFO = 'false'

[phases.install]
cmds = [
  'npm install'
]

[phases.build]
cmds = [
  'npm run build:css',
  'hugo --config hugo.yaml --minify'
]

[[nixpacks.included_files]]
paths = ["/public"]